steps:
  # Step 1: Install dependencies with legacy-peer-deps
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing dependencies with legacy-peer-deps..."
        npm install --legacy-peer-deps
    dir: "Frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: Build frontend
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        npm run build
    dir: "Frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "Frontend"

options:
  logging: CLOUD_LOGGING_ONLY
